title: fivetwoseven # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  
theme: jekyll-theme-midnight
google_analytics: UA-33714406-1 # your Google Analytics tracking ID here
